import { cn } from "@/lib/utils";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import { getSessions } from "./actions";
import Providers from "@/lib/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const navbarSessions = await getSessions().then((data) =>
    data.map((s) => ({
      title: s.title,
      href: s.id,
      description: s.description || "",
    }))
  );

  return (
    <html lang="en">
      <body className={cn(inter.className, "tracking-tight")}>
        <Providers>
          <div className="grid min-h-screen items-start">
            <Navbar sessions={navbarSessions} />
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
