import { cn } from "@/lib/utils";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import { getLogs, getTemplates, getWorkouts } from "./actions";
import { ClerkProvider } from "@clerk/nextjs";
import { Providers as ThemeAndQueryProvider } from "@/lib/providers";
import { dark } from "@clerk/themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const templates = await getTemplates();
  const workouts = await getWorkouts();
  const logs = await getLogs().then((data) =>
    data
      .filter(
        (item, i, arr) =>
          arr.findIndex((each) => each.title === item.title) === i
      )
      .sort((a, b) => a.title?.localeCompare(b.title))
  );

  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
    >
      <html lang="en">
        <body className={cn(inter.className, "tracking-tight")}>
          <ThemeAndQueryProvider>
            <div className="grid min-h-screen items-start">
              <Navbar
                initialTemplates={templates}
                initialWorkouts={workouts}
                initialLogs={logs}
              />
              <div className="space-y-10 p-10 lg:px-20">{children}</div>
            </div>
          </ThemeAndQueryProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
